### ISSUE TITLE
live demo

### ISSUE THREAD

**Issue by FND** [Heydon/bruck#2]
This project is not just an excellent idea, but also nicely executed - bravo! (Not that I'd expect any less from you... 😉 )

It would be nice if there was a demo I could link people to, so they don't have to clone the repo locally.

Thanks to [GitHub Pages](https://pages.github.com), this should be pretty straightforward:

```
$ git checkout -b gh-pages

# optionally make `demo.html` the entry point
$ git mv demo.html index.html
$ git commit -m "demo page as entry point for GitHub Pages"

$ git push origin gh-pages
```

Shortly after, the site should be available at https://heydon.github.io/bruck/. The downside, of course, is that continually updating that branch can be a bit of a pain - but you might consider making it the [default branch](https://github.com/Heydon/bruck/settings/branches).

(Apologies if you already knew all this.)

**Comment by Heydon** [comment]
@FND Good idea. I'll get onto this.

**Comment by MrKuzio** [comment]
It would be nice to have the demo linked from the README.md, or a list of projects using `bruck` in real-life.

**Comment by Heydon** [comment]
@FND @MrKuzio I have set up a build script which copies the `editor.html` and assets into the /docs folder and serves them. It's linked in the README (thanks for the suggestion!)

https://heydon.github.io/bruck/

The editor is simple (just a styled textarea) but I think it does the trick for now. Something a bit more codepen-like, with syntax highlighting and the ability to <kbd>tab</kbd> indent would be nice later on...

**Comment by FND** [comment]
Looking good, thank you!

I've noticed that in Firefox, `all: initial` results in line breaks within the `<textarea>` being swallowed. Applying `white-space: pre` fixes that. ¯\\\_(ツ)_/¯

**Comment by Heydon** [comment]
@FND Weird - I noticed that too and thought I fixed it. Was stung by specificity, though. Just pushed a fix to master. Thanks!

**Comment by Heydon** [comment]
@FND LOL, whoops. Just pushed that. Firefox looking good.
